config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands
  resources :albums
  resources :tracks
end

app/models/album.rb
class Album < ActiveRecord::Base

belongs_to(
  :band,
  class_name: 'Band',

  primary_key: :id,
  foreign_key: :band_id
)

has_many(
  :tracks,
  class_name: 'Track',

  primary_key: :id,
  foreign_key: :album_id
)

end

app/models/band.rb
class Band < ActiveRecord::Base

  has_many(
    :albums,
    class_name: 'Album',

    primary_key: :id,
    foreign_key: :band_id
  )

  has_many(
    :tracks,
    through: :albums,
    source: :tracks
  )
end

app/models/track.rb
class Track < ActiveRecord::Base

  belongs_to(
    :album,
    class_name: 'Album',

    primary_key: :id,
    foreign_key: :album_id
  )

  has_one(
    :band,
    through: :album,
    source: :band
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, uniqueness: true, presence: true
  validates :password_digest, presence: true
  validates :session_token, uniqueness: { scope: :session_token }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(params)
    email, pword = params[:email], params[:password]
    user = User.find_by(email: email)
    user = nil unless user && user.is_password?(pword)
    user
  end

  def self.random_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.random_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token = User.random_token unless self.session_token
  end

  def is_password?(pword)
    BCrypt::Password.new(password_digest).is_password?(pword)
  end

  def password=(pword)
    @password = pword
    self.password_digest = BCrypt::Password.create(pword)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    render :new
  end

  def show
    @album = Album.find(params[:id])
    redirect_to band_url(@album.band)
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    found = User.find_by(session_token: session[:session_token])
    return nil unless found
    @user = found
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout_user!
    session[:session_token] = nil
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params)
    if @user
      login_user!(@user)
      redirect_to bands_url
    else
      render :new
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    render :new
  end

  def show
    @track = Track.find(params[:id])
    redirect_to band_url(@track.band)
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      render :new
    end
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def show
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to bands_url
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_authenticity_token.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

app/views/albums/new.html.erb
<h2>Record a new Album</h2>

<form action="<%=albums_url%>", method="post">

  <%= render "authenticity_token" %>

  <label for="album_name">
    Name:
  </label>
  <input
    type="text"
    name="album[name]"
    id="album_name">
  <br>

  <label for="album_band_id">
    Band:
  </label>
  <select
    type="option"
    name="album[band_id]"
    id="album_band_id">
  <option></option>
  <% Band.all.each do |band| %>
    <option
    value="<%= band.id %>">
    <%= band.name %>
    </option>
  <% end %>
</select>

  <input type="submit" value="Submit">

</form>

app/views/bands/_authenticity_token.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

app/views/bands/index.html.erb
<h2>Bands</h2>

<% Band.all.each do |band| %>
  <li>
    <%= link_to band.name, band_url(band) %>
    <ul>
      <% band.albums.each do |album| %>
        <li> <%= link_to album.name, band_url(band) %></li>
        <ul>
          <% album.tracks.each do |track| %>
            <li> <%= link_to track.name, band_url(band) %></li>
          <% end %>
        </ul>
      <% end %>
    </ul>
  </li>
<% end %>

<br><br>

<%= link_to "New Band", new_band_url %>
<br>
<%= link_to "New Album", new_album_url %>
<br>
<%= link_to "New Track", new_track_url %>

app/views/bands/new.html.erb
<h2>Record a new Band</h2>

<form action="<%=bands_url%>", method="post">

  <%= render "authenticity_token" %>

  <label>
    Name:
  </label>
  <input
    type="text"
    name="band[name]"
    id="band_name">
  <br>

  <input type="submit" value="Submit">

</form>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>

<% @band.albums.each do |album| %>
  <%= album.name %>
  <% album.tracks.each do |track| %>
  <ul>
    <li><%= track.name %></li>
  </ul>
  <% end %>
  <br>
<% end %>

app/views/layouts/_authenticity_token.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Napster2016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <form action=" <%=session_url%>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Sign Out">
    <%= render "authenticity_token" %>

  </form>
<% end %>

<%= yield %>

<br>
<%= link_to "Back to Index", bands_url %>

</body>
</html>

app/views/tracks/_authenticity_token.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

app/views/tracks/new.html.erb
<h2>Record a new Track</h2>

<form action="<%=tracks_url%>", method="post">

  <%= render "authenticity_token" %>

  <label for="track_name">
    Name:
  </label>
  <input
    type="text"
    name="track[name]"
    id="track_name">
  <br>

  <label for="track_album_id">
    Album:
  </label>
  <select
    type="option"
    name="track[album_id]"
    id="track_album_id">
  <option></option>
  <% Album.all.each do |album| %>
    <option
    value="<%= album.id %>">
    <%= album.name %>
    </option>
  <% end %>
</select>

  <input type="submit" value="Submit">

</form>

app/views/users/_authenticity_token.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

app/views/users/new.html.erb
<h2>Welcome, new user!</h2>

<form action="<%=users_url%>", method="post">

  <%= render "authenticity_token" %>

  <label>
    Email:
  </label>
  <input
    type="text"
    name="user[email]"
    id="user_email">
  <br>

  <label>
    Password:
  </label>
  <input
    type="password"
    name="user[password]"
    id="user_password">
  <br>

  <input type="submit" value="Register">

</form>

app/views/users/show.html.erb
<h2>Your Music</h2>

You for sure don't have any songs yet.